apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pxe-demo
  name: pxe-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: pxe-demo
  type: LoadBalancer
status:
  loadBalancer: {}